apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson:  ewoJImF1dGhzIjogewoJCSJ2YWxheHk0Ny5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiWjJGdVpYTm9lV0ZrWVhadFlYSmhZbTlwYm1FNlRVZFpZV1JoZGtBME56TTAiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson